[build.environment]
    REACT_APP_DEPLOYMENT_TYPE="STAGING"
    REACT_APP_ALICENET_RPC_ENDPOINT_LOCAL="http://localhost:8887/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_STAGING="https://edge.staging.alice.net/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_PRODUCTION="https://edge.alice.net/v1/"

    REACT_APP_GITHUB_URL="https://github.com/madhive"
    REACT_APP_WHITE_PAPER_URL="https://www.madnetwork.com/madnetwork-download-whitepaper"
    REACT_APP_ALICENET_URL="https://www.alice.net"

    REACT_APP_WALLET_LINUX_URL="https://github.com/alicenet/wallet/releases/download/v1.0.4-alpha/linux_alicenetwallet_x64.zip"
    REACT_APP_WALLET_MAC_URL="https://github.com/alicenet/wallet/releases/download/v1.0.4-alpha/mac_alicenetwallet.dmg"
    REACT_APP_WALLET_WINDOWS_URL="https://github.com/alicenet/wallet/releases/download/v1.0.4-alpha/windows_alicenetwallet_x64.exe"

    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
