[build.environment]
    REACT_APP_DEPLOYMENT_TYPE="LOCAL"
    REACT_APP_ALICENET_RPC_ENDPOINT_LOCAL="https://api.alicenet.duckdns.org/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_STAGING="https://testnet.edge.mnexplore.com/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_PRODUCTION="https://edge.mnexplore.com/v1/"
    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
