[build.environment]
    REACT_APP_DEPLOYMENT_TYPE="PRODUCTION"
    REACT_APP_ALICENET_RPC_ENDPOINT_LOCAL="http://localhost:8887/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_STAGING="https://edge.staging.alice.net/v1/"
    REACT_APP_ALICENET_RPC_ENDPOINT_PRODUCTION="https://edge.mnexplore.com/v1/"
    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
