module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  important: true,
  theme: {
    extend: {
      colors: {
        darkGrey: '#2D2D2D',
        lightGrey: '#DEDEDE',
        primary: '#00FFD1',
      },
    },
  },
  plugins: [],
  corePlugins: [
      'animation',
      'alignContent',
      'alignItems',
      'alignSelf',
      'backgroundColor',
      'backgroundOpacity',
      'borderColor',
      'borderRadius',
      'borderStyle',
      'borderWidth',
      'boxShadow',
      'cursor',
      'display',
      'flex',
      'flexDirection',
      'flexShrink',
      'flexWrap',
      'flexGrow',
      'fontSize',
      'fontStyle',
      'fontWeight',
      'fontFamily',
      'gap',
      'height',
      'inset',
      'justifyContent',
      'justifyItems',
      'justifySelf',
      'inset',
      'margin',
      'maxHeight',
      'maxWidth',
      'minHeight',
      'minWidth',
      'outline',
      'overflow',
      'opacity',
      'overscrollBehavior',
      'padding',
      'position',
      'pointerEvents',
      'resize',
      'rotate',
      'textAlign',
      'textColor',
      'textDecoration',
      'textOverflow',
      'textTransform',
      'textIndent',
      'transform',
      'transitionProperty',
      'transitionDuration',
      'whitespace',
      'width',
      'wordBreak',
      'zIndex',
  ]
}
